// Main definition of the postal address
// Taken from https://web.archive.org/web/20230101002052/https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form#Example
<postal-address> = <name-part> <street-address> <zip-part>
<name-part> ::= <personal-part> " " <last-name> " " <opt-suffix-part> "\n" | <personal-part> " " <name-part>
<personal-part> ::= <initial> "." | <first-name>
<street-address> ::= <house-num> " " <street-name> " " <opt-apt-num> "\n"
<zip-part> ::= <town-name> ", " <state-code> " " <ZIP-code> "\n"
<opt-suffix-part> ::= "Sr." | "Jr." | <roman-numeral> | ""
<opt-apt-num> ::= <apt-num> | ""

// Just some test data
<funny-numbers-haha> ::= "69" | "420" | "1337" | "69420" | "80085"
<apt-num> ::= <funny-numbers-haha>
<roman-numeral> ::= "I" | "II" | "III" | "IV" | "V" | "VI"
<first-name> ::= "Wade" | "Dave" | "Seth" | "Ivan" | "Riley" | "Gilbert" | "Jorge" | "Dan"
<initial> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
<last-name> ::= "Smith" | "Jones" | "Williams" | "Taylor" | "Brown" | "Davies" | "Evans" | "Thomas"
<house-num> ::= <funny-numbers-haha>
<street-name> ::= "MEDITATION LANE" | "SILVER CANOE WAY" | "GENTLE RAIN DRIVE" | "LOCH NESS ROAD" | "GRANDIOSE DRIVE" | "MELODY DRIVE" | "MISTLETOE LANE" | "GOLDEN TROUT WAY" | "CHARDONNAY DRIVE" | "DIXIE AVENUE"
<town-name> ::= "Balls Creek" | "Sober Island" | "Mushaboom" | "Lower Economy"
<state-code> ::= "AD" | "AR" | "AS" | "BR" | "CG" | "DL" | "GA" | "GJ" | "HR" | "HP" | "JK" | "JH" | "KA" | "KL" | "LD" | "MP" | "MH" | "MN" | "ML" | "MZ" | "NL" | "OD" | "PY" | "PB" | "RJ" | "SK" | "TN" | "TS" | "TR" | "UP" | "UK" | "WB"
<ZIP-code> ::= "10001" | "10002" | "11101" | "11212" | "23220" | "33101" | "10003" | "20001" | "11201" | "10011"
